<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>Object.DirectX</AssemblyName>
    <RootNamespace>Object.DirectX</RootNamespace>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NO_WINFORMS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetZip.OpenBVE" Version="1.17.2" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../AssimpParser/AssimpParser.csproj" />
    <ProjectReference Include="../../OpenBveApi/OpenBveApi.csproj" />
  </ItemGroup>

  <Target Name="AfterBuild">
      <ItemGroup>
        <OutputFiles Include="$(TargetDir)$(TargetName).*" />
      </ItemGroup>
      <Move SourceFiles="@(OutputFiles)" DestinationFolder="$(TargetDir)Data\Plugins\" />
    </Target>

</Project>
