<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>TrainManager</AssemblyName>
    <RootNamespace>TrainManager</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NO_WINFORMS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.NetNamedPipe" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibRender2\LibRender2.csproj" />
    <ProjectReference Include="..\OpenBveApi\OpenBveApi.csproj" />
    <ProjectReference Include="..\Plugins\Formats.Msts\Formats.Msts.csproj" />
    <ProjectReference Include="..\RouteManager2\RouteManager2.csproj" />
    <ProjectReference Include="..\SoundManager\SoundManager.csproj" />
  </ItemGroup>
</Project>