<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>LibRender2</AssemblyName>
    <RootNamespace>LibRender2</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK-OpenBVE" Version="1.0.4" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.20.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenBveApi\OpenBveApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\Shaders\default.frag" Link="Shaders\default.frag" />
    <EmbeddedResource Include="..\..\assets\Shaders\default.vert" Link="Shaders\default.vert" />
    <EmbeddedResource Include="..\..\assets\Shaders\picking.frag" Link="Shaders\picking.frag" />
    <EmbeddedResource Include="..\..\assets\Shaders\rectangle.frag" Link="Shaders\rectangle.frag" />
    <EmbeddedResource Include="..\..\assets\Shaders\rectangle.vert" Link="Shaders\rectangle.vert" />
    <EmbeddedResource Include="..\..\assets\Shaders\text.vert" Link="Shaders\text.vert" />
    <EmbeddedResource Include="..\..\assets\Shaders\shadow_depth.vert" Link="Shaders\shadow_depth.vert" />
    <EmbeddedResource Include="..\..\assets\Shaders\shadow_depth.frag" Link="Shaders\shadow_depth.frag" />
  </ItemGroup>
</Project>