<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>Formats.OpenBve</AssemblyName>
    <RootNamespace>Formats.OpenBve</RootNamespace>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/Data/Formats/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/Data/Formats/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NO_WINFORMS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../OpenBveApi/OpenBveApi.csproj" />
  </ItemGroup>

</Project>
