<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>LBAHeader</AssemblyName>
    <RootNamespace>LBAHeader</RootNamespace>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/DevTools/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/DevTools/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NO_WINFORMS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.3" />
  </ItemGroup>

</Project>
