<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>TrainEditor</AssemblyName>
    <RootNamespace>TrainEditor</RootNamespace>
    <OutputType>WinExe</OutputType>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>..\..\assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OpenBveApi/OpenBveApi.csproj" />
    <ProjectReference Include="../Plugins/Formats.OpenBve/Formats.OpenBve.csproj" />
    <ProjectReference Include="../TrainManager/TrainManager.csproj" />
  </ItemGroup>

  <Target Name="AfterBuild">
      
      
      <ItemGroup>
        <AssetFiles Include="$(SolutionDir)assets\**\*.*" />
      </ItemGroup>
      <Copy SkipUnchangedFiles="true" SourceFiles="@(AssetFiles)" DestinationFiles="@(AssetFiles-&gt;'$(TargetDir)Data\%(RecursiveDir)%(Filename)%(Extension)')" />
    </Target>

</Project>
