<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <AssemblyName>Train.MsTs</AssemblyName>
    <RootNamespace>Train.MsTs</RootNamespace>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <DefineConstants>$(DefineConstants);NO_WINFORMS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="SharpCompress" Version="0.48.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../LibRender2/LibRender2.csproj" />
    <ProjectReference Include="../../OpenBveApi/OpenBveApi.csproj" />
    <ProjectReference Include="../../SoundManager/SoundManager.csproj" />
    <ProjectReference Include="../../TrainManager/TrainManager.csproj" />
    <ProjectReference Include="../Formats.Msts/Formats.Msts.csproj" />
  </ItemGroup>

  <Target Name="AfterBuild">
      <ItemGroup>
        <OutputFiles Include="$(TargetDir)$(TargetName).*" />
      </ItemGroup>
      <Move SourceFiles="@(OutputFiles)" DestinationFolder="$(TargetDir)Data\Plugins\" />
    </Target>

</Project>
