<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DenshaDeGoInput</AssemblyName>
    <RootNamespace>DenshaDeGoInput</RootNamespace>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>$(SolutionDir)bin_debug/</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>$(SolutionDir)bin_release/</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibUsbDotNet" Version="2.2.29" />
    <PackageReference Include="OpenTK-OpenBVE" Version="1.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../OpenBveApi/OpenBveApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Drivers/99-ps2-train-controllers.rules" />
    <EmbeddedResource Include="Drivers/Ryojouhen.cfg" />
    <EmbeddedResource Include="Drivers/Shinkansen.cfg" />
    <EmbeddedResource Include="Drivers/Type2.cfg" />
    <EmbeddedResource Include="Drivers/TrainMascon.cfg" />
    <EmbeddedResource Include="Drivers/MTC.cfg" />
  </ItemGroup>

  <Target Name="AfterBuild">
      <ItemGroup>
        <OutputFiles Include="$(TargetDir)$(TargetName).*" />
      </ItemGroup>
      <Move SourceFiles="@(OutputFiles)" DestinationFolder="$(TargetDir)Data\InputDevicePlugins\" />
    </Target>

</Project>
